### PR TITLE
Register Fragment buttons

### PR DESCRIPTION
**Pull request by Bettyabera**
I added a login button, made it bold, and tried to match the login page. The colors have been modified. However, I didn't switch the screen's primary color to blue.  And the other thing is the icon. I wanted to add them but don't know what to put for the nickname and last name. let me know if there is anything I can do to improve.

### CODE REVIEW

**Comment by krobison10** [comment]
-You should go a bit narrower on the fields; configure the ConstraintLayout to make the fields have a left and right spacing of 32dp, like in the login fragment.
-Make the buttons constrained to the bottom of the fragment. Maybe try 32dp?
-Make sure to have the edges of the buttons line up with the edges of the fields that are above them.

-Additionally, I would make the font color of the register button white.

-Don't forget some text at the top explaining what is going on.

-Lastly, remove the nickname field for now, I don't think the database accommodates that yet.

**Comment by krobison10** [comment]
Tip for the width: make one have a left and right spacing of 32dp, and have the left and right constraints of each successive field be attached to the left and right of the previous, which allows you to only have to set two values for all of them to have it.

**Comment by krobison10** [comment]
I made a quick refactoring according to material3 spec, if you're okay with how it looks then you're good to merge and close this PR

**Comment by jaspersn** [comment]
I find the yellow text a bit hard to read. Maybe use blue in both places like the purple in the login fragment?

image
image

**Pull request merged**
